default:
  image: registry.ops.mobit.ir/base/docker:latest
stages:
  - build_base
  - build
  - build_nginx
  - deploy
  - migrate

variables:
  IMAGE_TAG_BASE: registry.ops.mobit.ir/avinox-dev/backendbase:latest
  IMAGE_TAG_DEV: registry.ops.mobit.ir/avinox-dev/backend:latest
  NGINX_IMAGE_TAG_DEV: registry.ops.mobit.ir/avinox-dev/nginx:latest

  IMAGE_TAG_LATEST: registry.ops.mobit.ir/avinox/backend:latest
  NGINX_IMAGE_TAG_LATEST: registry.ops.mobit.ir/avinox/nginx:latest

build_base_image:
  stage: build_base
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/ --username root --password-stdin
  script:
    - docker build -f Dockerfile.base . -t $IMAGE_TAG_BASE
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz composer-install/ || $CI_COMMIT_MESSAGE =~ /plz dev.composer-install/ || $CI_PIPELINE_SOURCE=="web"'
      when: always
    - when: never

build:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/  --username root --password-stdin
  script:
    - docker build --no-cache -t $IMAGE_TAG_LATEST -f Dockerfile .
    - docker push $IMAGE_TAG_LATEST
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz build/ || $CI_COMMIT_MESSAGE =~ /plz composer-install/ '
      when: always
    - when: never

build-dev:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/  --username root --password-stdin
  script:
    - docker build --no-cache -t $IMAGE_TAG_DEV -f Dockerfile.dev .
    - docker push $IMAGE_TAG_DEV
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz dev.build/ || $CI_COMMIT_MESSAGE =~ /plz dev.composer-install/ '
      when: always
    - when: never

nginx-build:
  stage: build_nginx
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/  --username root --password-stdin
  script:
    - docker build -t $NGINX_IMAGE_TAG_LATEST  -f Dockerfile.nginx .
    - docker push $NGINX_IMAGE_TAG_LATEST
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz build/ || $CI_COMMIT_MESSAGE =~ /plz composer-install/ '
      when: always
    - when: never

nginx-build-dev:
  stage: build_nginx
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/  --username root --password-stdin
  script:
    - docker build -t $NGINX_IMAGE_TAG_DEV  -f Dockerfile.nginx.dev .
    - docker push $NGINX_IMAGE_TAG_DEV
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz dev.build/ || $CI_COMMIT_MESSAGE =~ /plz dev.composer-install/ '
      when: always
    - when: never

deploy:
  stage: deploy
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/ --username root --password-stdin
  script:
    - |
      docker service update --force --with-registry-auth avinox_backend --image $IMAGE_TAG_LATEST
      docker service update --force --with-registry-auth avinox_nginx --image $NGINX_IMAGE_TAG_LATEST
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz build/ || $CI_COMMIT_MESSAGE =~ /plz composer-install/ '
      when: on_success
    - when: never

deploy-dev:
  stage: deploy
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login http://registry.ops.mobit.ir/ --username root --password-stdin
  script:
    - |
      docker service update --force --with-registry-auth avinox_dev_backend --image $IMAGE_TAG_DEV
      docker service update --force --with-registry-auth avinox_dev_nginx --image $NGINX_IMAGE_TAG_DEV
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz dev.build/ || $CI_COMMIT_MESSAGE =~ /plz dev.composer-install/ '
      when: on_success
    - when: never

migrate_up:
  stage: migrate
  script: 
    - docker exec $(docker ps |  grep "avinox_backend".* | awk '{print $1}' | head -1)  yii migrate --interactive=0
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz migrate-up/'
      when: on_success
    - when: never

migrate_down:
  stage: migrate
  script: 
    - docker exec $(docker ps --format '{{.Names}}' |  grep "avinox_backend.*"  | head -1) yii migrate/down --interactive=0
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz migrate-down/ '
      when: on_success
    - when: never

migrate_up_dev:
  stage: migrate
  script: 
    - docker exec $(docker ps --format '{{.Names}}' | grep "avinox_dev_backend.*"  | head -1) yii migrate --interactive=0
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz dev.migrate-up/'
      when: always
    - when: never

migrate_down_dev:
  stage: migrate
  script: 
    - docker exec $(docker ps --format '{{.Names}}' | grep "avinox_dev_backend.*" | head -1) yii migrate/down --interactive=0
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /plz dev.migrate-down/ '
      when: always
    - when: never

